# upstream : window환경에서 기동중인 Waitress TCP 주소(127.0.0.1:8000)를 연결
# Nginx window버전은 UNIX도메인 소켓 방식을 지원하지 않아서 TCP방식을 사용
upstream django_app {
    server 127.0.0.1:8000
}

server {
    listn 80;
    server_name localhost;

    # 파일업로드 크기제한 해제(50M)
    client_max_body_size 50M;

    # 로깅파일 설정(Window Nginx의 기본 logs 폴더 저장)
    access_log logs/django_access.log;
    error_log logs/django_error.log;

    # 모든 일반 동적요청을 Waitress WAS로 프록싱
    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwared_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        # 리다이렉트 충돌 방지
        proxy_redirect off;

        # 정의된 TCP upstream으로 패스
        proxy_pass http://django_app;
    }
}